package edu.pitt.medschool.model.dto;

import java.util.Date;

public class Downsample {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column downsample.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column downsample.alias
	 * @mbg.generated
	 */
	private String alias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column downsample.period
	 * @mbg.generated
	 */
	private Integer period;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column downsample.duration
	 * @mbg.generated
	 */
	private Integer duration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column downsample.origin
	 * @mbg.generated
	 */
	private Integer origin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column downsample.min_total_bin_threshold
	 * @mbg.generated
	 */
	private Integer minTotalBinThreshold;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column downsample.min_every_bin_thershold
	 * @mbg.generated
	 */
	private Integer minEveryBinThershold;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column downsample.is_downsample_first
	 * @mbg.generated
	 */
	private Boolean isDownsampleFirst;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column downsample.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column downsample.update_time
	 * @mbg.generated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column downsample.id
	 * @return  the value of downsample.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column downsample.id
	 * @param id  the value for downsample.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column downsample.alias
	 * @return  the value of downsample.alias
	 * @mbg.generated
	 */
	public String getAlias() {
		return alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column downsample.alias
	 * @param alias  the value for downsample.alias
	 * @mbg.generated
	 */
	public void setAlias(String alias) {
		this.alias = alias == null ? null : alias.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column downsample.period
	 * @return  the value of downsample.period
	 * @mbg.generated
	 */
	public Integer getPeriod() {
		return period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column downsample.period
	 * @param period  the value for downsample.period
	 * @mbg.generated
	 */
	public void setPeriod(Integer period) {
		this.period = period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column downsample.duration
	 * @return  the value of downsample.duration
	 * @mbg.generated
	 */
	public Integer getDuration() {
		return duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column downsample.duration
	 * @param duration  the value for downsample.duration
	 * @mbg.generated
	 */
	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column downsample.origin
	 * @return  the value of downsample.origin
	 * @mbg.generated
	 */
	public Integer getOrigin() {
		return origin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column downsample.origin
	 * @param origin  the value for downsample.origin
	 * @mbg.generated
	 */
	public void setOrigin(Integer origin) {
		this.origin = origin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column downsample.min_total_bin_threshold
	 * @return  the value of downsample.min_total_bin_threshold
	 * @mbg.generated
	 */
	public Integer getMinTotalBinThreshold() {
		return minTotalBinThreshold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column downsample.min_total_bin_threshold
	 * @param minTotalBinThreshold  the value for downsample.min_total_bin_threshold
	 * @mbg.generated
	 */
	public void setMinTotalBinThreshold(Integer minTotalBinThreshold) {
		this.minTotalBinThreshold = minTotalBinThreshold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column downsample.min_every_bin_thershold
	 * @return  the value of downsample.min_every_bin_thershold
	 * @mbg.generated
	 */
	public Integer getMinEveryBinThershold() {
		return minEveryBinThershold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column downsample.min_every_bin_thershold
	 * @param minEveryBinThershold  the value for downsample.min_every_bin_thershold
	 * @mbg.generated
	 */
	public void setMinEveryBinThershold(Integer minEveryBinThershold) {
		this.minEveryBinThershold = minEveryBinThershold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column downsample.is_downsample_first
	 * @return  the value of downsample.is_downsample_first
	 * @mbg.generated
	 */
	public Boolean getIsDownsampleFirst() {
		return isDownsampleFirst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column downsample.is_downsample_first
	 * @param isDownsampleFirst  the value for downsample.is_downsample_first
	 * @mbg.generated
	 */
	public void setIsDownsampleFirst(Boolean isDownsampleFirst) {
		this.isDownsampleFirst = isDownsampleFirst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column downsample.create_time
	 * @return  the value of downsample.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column downsample.create_time
	 * @param createTime  the value for downsample.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column downsample.update_time
	 * @return  the value of downsample.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column downsample.update_time
	 * @param updateTime  the value for downsample.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table downsample
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Downsample other = (Downsample) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getAlias() == null ? other.getAlias() == null : this.getAlias().equals(other.getAlias()))
				&& (this.getPeriod() == null ? other.getPeriod() == null : this.getPeriod().equals(other.getPeriod()))
				&& (this.getDuration() == null ? other.getDuration() == null
						: this.getDuration().equals(other.getDuration()))
				&& (this.getOrigin() == null ? other.getOrigin() == null : this.getOrigin().equals(other.getOrigin()))
				&& (this.getMinTotalBinThreshold() == null ? other.getMinTotalBinThreshold() == null
						: this.getMinTotalBinThreshold().equals(other.getMinTotalBinThreshold()))
				&& (this.getMinEveryBinThershold() == null ? other.getMinEveryBinThershold() == null
						: this.getMinEveryBinThershold().equals(other.getMinEveryBinThershold()))
				&& (this.getIsDownsampleFirst() == null ? other.getIsDownsampleFirst() == null
						: this.getIsDownsampleFirst().equals(other.getIsDownsampleFirst()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table downsample
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getAlias() == null) ? 0 : getAlias().hashCode());
		result = prime * result + ((getPeriod() == null) ? 0 : getPeriod().hashCode());
		result = prime * result + ((getDuration() == null) ? 0 : getDuration().hashCode());
		result = prime * result + ((getOrigin() == null) ? 0 : getOrigin().hashCode());
		result = prime * result + ((getMinTotalBinThreshold() == null) ? 0 : getMinTotalBinThreshold().hashCode());
		result = prime * result + ((getMinEveryBinThershold() == null) ? 0 : getMinEveryBinThershold().hashCode());
		result = prime * result + ((getIsDownsampleFirst() == null) ? 0 : getIsDownsampleFirst().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}
}