package edu.pitt.medschool.model.dto;

import java.util.Date;

public class DownsampleMeta {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column downsample_meta.id
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column downsample_meta.query_id
     * @mbg.generated
     */
    private Integer queryId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column downsample_meta.key
     * @mbg.generated
     */
    private String key;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column downsample_meta.value
     * @mbg.generated
     */
    private String value;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column downsample_meta.create_time
     * @mbg.generated
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column downsample_meta.update_time
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column downsample_meta.id
     * @return  the value of downsample_meta.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column downsample_meta.id
     * @param id  the value for downsample_meta.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column downsample_meta.query_id
     * @return  the value of downsample_meta.query_id
     * @mbg.generated
     */
    public Integer getQueryId() {
        return queryId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column downsample_meta.query_id
     * @param queryId  the value for downsample_meta.query_id
     * @mbg.generated
     */
    public void setQueryId(Integer queryId) {
        this.queryId = queryId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column downsample_meta.key
     * @return  the value of downsample_meta.key
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column downsample_meta.key
     * @param key  the value for downsample_meta.key
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column downsample_meta.value
     * @return  the value of downsample_meta.value
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column downsample_meta.value
     * @param value  the value for downsample_meta.value
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column downsample_meta.create_time
     * @return  the value of downsample_meta.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column downsample_meta.create_time
     * @param createTime  the value for downsample_meta.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column downsample_meta.update_time
     * @return  the value of downsample_meta.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column downsample_meta.update_time
     * @param updateTime  the value for downsample_meta.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_meta
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DownsampleMeta other = (DownsampleMeta) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getQueryId() == null ? other.getQueryId() == null : this.getQueryId().equals(other.getQueryId()))
                && (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()))
                && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_meta
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getQueryId() == null) ? 0 : getQueryId().hashCode());
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}