package edu.pitt.medschool.model.dto;

public class ImportProgress extends ImportProgressKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column import_progress.status
     * @mbg.generated
     */
    private String status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column import_progress.all_percent
     * @mbg.generated
     */
    private Double allPercent;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column import_progress.this_percent
     * @mbg.generated
     */
    private Double thisPercent;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column import_progress.all_file_size
     * @mbg.generated
     */
    private Long allFileSize;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column import_progress.this_file_size
     * @mbg.generated
     */
    private Long thisFileSize;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column import_progress.file_path
     * @mbg.generated
     */
    private String filePath;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column import_progress.status
     * @return  the value of import_progress.status
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column import_progress.status
     * @param status  the value for import_progress.status
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column import_progress.all_percent
     * @return  the value of import_progress.all_percent
     * @mbg.generated
     */
    public Double getAllPercent() {
        return allPercent;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column import_progress.all_percent
     * @param allPercent  the value for import_progress.all_percent
     * @mbg.generated
     */
    public void setAllPercent(Double allPercent) {
        this.allPercent = allPercent;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column import_progress.this_percent
     * @return  the value of import_progress.this_percent
     * @mbg.generated
     */
    public Double getThisPercent() {
        return thisPercent;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column import_progress.this_percent
     * @param thisPercent  the value for import_progress.this_percent
     * @mbg.generated
     */
    public void setThisPercent(Double thisPercent) {
        this.thisPercent = thisPercent;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column import_progress.all_file_size
     * @return  the value of import_progress.all_file_size
     * @mbg.generated
     */
    public Long getAllFileSize() {
        return allFileSize;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column import_progress.all_file_size
     * @param allFileSize  the value for import_progress.all_file_size
     * @mbg.generated
     */
    public void setAllFileSize(Long allFileSize) {
        this.allFileSize = allFileSize;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column import_progress.this_file_size
     * @return  the value of import_progress.this_file_size
     * @mbg.generated
     */
    public Long getThisFileSize() {
        return thisFileSize;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column import_progress.this_file_size
     * @param thisFileSize  the value for import_progress.this_file_size
     * @mbg.generated
     */
    public void setThisFileSize(Long thisFileSize) {
        this.thisFileSize = thisFileSize;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column import_progress.file_path
     * @return  the value of import_progress.file_path
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column import_progress.file_path
     * @param filePath  the value for import_progress.file_path
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@Override public boolean equals(Object that){if (this == that){return true;}if (that == null){return false;}if (getClass() != that.getClass()){return false;}ImportProgress other=(ImportProgress)that;return (this.getFilename() == null?other.getFilename() == null:this.getFilename().equals(other.getFilename())) && (this.getTimestamp() == null?other.getTimestamp() == null:this.getTimestamp().equals(other.getTimestamp())) && (this.getUuid() == null?other.getUuid() == null:this.getUuid().equals(other.getUuid())) && (this.getStatus() == null?other.getStatus() == null:this.getStatus().equals(other.getStatus())) && (this.getAllPercent() == null?other.getAllPercent() == null:this.getAllPercent().equals(other.getAllPercent())) && (this.getThisPercent() == null?other.getThisPercent() == null:this.getThisPercent().equals(other.getThisPercent())) && (this.getAllFileSize() == null?other.getAllFileSize() == null:this.getAllFileSize().equals(other.getAllFileSize())) && (this.getThisFileSize() == null?other.getThisFileSize() == null:this.getThisFileSize().equals(other.getThisFileSize())) && (this.getFilePath() == null?other.getFilePath() == null:this.getFilePath().equals(other.getFilePath()));}

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@Override public int hashCode(){final int prime=31;int result=1;result=prime * result + ((getFilename() == null)?0:getFilename().hashCode());result=prime * result + ((getTimestamp() == null)?0:getTimestamp().hashCode());result=prime * result + ((getUuid() == null)?0:getUuid().hashCode());result=prime * result + ((getStatus() == null)?0:getStatus().hashCode());result=prime * result + ((getAllPercent() == null)?0:getAllPercent().hashCode());result=prime * result + ((getThisPercent() == null)?0:getThisPercent().hashCode());result=prime * result + ((getAllFileSize() == null)?0:getAllFileSize().hashCode());result=prime * result + ((getThisFileSize() == null)?0:getThisFileSize().hashCode());result=prime * result + ((getFilePath() == null)?0:getFilePath().hashCode());return result;}
}