package edu.pitt.medschool.model.dto;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class MedicationExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table medication
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table medication
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table medication
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medication
	 * @mbg.generated
	 */
	public MedicationExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medication
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medication
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medication
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medication
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medication
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medication
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medication
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medication
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medication
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medication
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table medication
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andInfusedVolIsNull() {
			addCriterion("infused_vol is null");
			return (Criteria) this;
		}

		public Criteria andInfusedVolIsNotNull() {
			addCriterion("infused_vol is not null");
			return (Criteria) this;
		}

		public Criteria andInfusedVolEqualTo(Integer value) {
			addCriterion("infused_vol =", value, "infusedVol");
			return (Criteria) this;
		}

		public Criteria andInfusedVolNotEqualTo(Integer value) {
			addCriterion("infused_vol <>", value, "infusedVol");
			return (Criteria) this;
		}

		public Criteria andInfusedVolGreaterThan(Integer value) {
			addCriterion("infused_vol >", value, "infusedVol");
			return (Criteria) this;
		}

		public Criteria andInfusedVolGreaterThanOrEqualTo(Integer value) {
			addCriterion("infused_vol >=", value, "infusedVol");
			return (Criteria) this;
		}

		public Criteria andInfusedVolLessThan(Integer value) {
			addCriterion("infused_vol <", value, "infusedVol");
			return (Criteria) this;
		}

		public Criteria andInfusedVolLessThanOrEqualTo(Integer value) {
			addCriterion("infused_vol <=", value, "infusedVol");
			return (Criteria) this;
		}

		public Criteria andInfusedVolIn(List<Integer> values) {
			addCriterion("infused_vol in", values, "infusedVol");
			return (Criteria) this;
		}

		public Criteria andInfusedVolNotIn(List<Integer> values) {
			addCriterion("infused_vol not in", values, "infusedVol");
			return (Criteria) this;
		}

		public Criteria andInfusedVolBetween(Integer value1, Integer value2) {
			addCriterion("infused_vol between", value1, value2, "infusedVol");
			return (Criteria) this;
		}

		public Criteria andInfusedVolNotBetween(Integer value1, Integer value2) {
			addCriterion("infused_vol not between", value1, value2, "infusedVol");
			return (Criteria) this;
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andChartDateIsNull() {
			addCriterion("chart_date is null");
			return (Criteria) this;
		}

		public Criteria andChartDateIsNotNull() {
			addCriterion("chart_date is not null");
			return (Criteria) this;
		}

		public Criteria andChartDateEqualTo(Date value) {
			addCriterion("chart_date =", value, "chartDate");
			return (Criteria) this;
		}

		public Criteria andChartDateNotEqualTo(Date value) {
			addCriterion("chart_date <>", value, "chartDate");
			return (Criteria) this;
		}

		public Criteria andChartDateGreaterThan(Date value) {
			addCriterion("chart_date >", value, "chartDate");
			return (Criteria) this;
		}

		public Criteria andChartDateGreaterThanOrEqualTo(Date value) {
			addCriterion("chart_date >=", value, "chartDate");
			return (Criteria) this;
		}

		public Criteria andChartDateLessThan(Date value) {
			addCriterion("chart_date <", value, "chartDate");
			return (Criteria) this;
		}

		public Criteria andChartDateLessThanOrEqualTo(Date value) {
			addCriterion("chart_date <=", value, "chartDate");
			return (Criteria) this;
		}

		public Criteria andChartDateIn(List<Date> values) {
			addCriterion("chart_date in", values, "chartDate");
			return (Criteria) this;
		}

		public Criteria andChartDateNotIn(List<Date> values) {
			addCriterion("chart_date not in", values, "chartDate");
			return (Criteria) this;
		}

		public Criteria andChartDateBetween(Date value1, Date value2) {
			addCriterion("chart_date between", value1, value2, "chartDate");
			return (Criteria) this;
		}

		public Criteria andChartDateNotBetween(Date value1, Date value2) {
			addCriterion("chart_date not between", value1, value2, "chartDate");
			return (Criteria) this;
		}

		public Criteria andDrugNameIsNull() {
			addCriterion("drug_name is null");
			return (Criteria) this;
		}

		public Criteria andDrugNameIsNotNull() {
			addCriterion("drug_name is not null");
			return (Criteria) this;
		}

		public Criteria andDrugNameEqualTo(String value) {
			addCriterion("drug_name =", value, "drugName");
			return (Criteria) this;
		}

		public Criteria andDrugNameNotEqualTo(String value) {
			addCriterion("drug_name <>", value, "drugName");
			return (Criteria) this;
		}

		public Criteria andDrugNameGreaterThan(String value) {
			addCriterion("drug_name >", value, "drugName");
			return (Criteria) this;
		}

		public Criteria andDrugNameGreaterThanOrEqualTo(String value) {
			addCriterion("drug_name >=", value, "drugName");
			return (Criteria) this;
		}

		public Criteria andDrugNameLessThan(String value) {
			addCriterion("drug_name <", value, "drugName");
			return (Criteria) this;
		}

		public Criteria andDrugNameLessThanOrEqualTo(String value) {
			addCriterion("drug_name <=", value, "drugName");
			return (Criteria) this;
		}

		public Criteria andDrugNameLike(String value) {
			addCriterion("drug_name like", value, "drugName");
			return (Criteria) this;
		}

		public Criteria andDrugNameNotLike(String value) {
			addCriterion("drug_name not like", value, "drugName");
			return (Criteria) this;
		}

		public Criteria andDrugNameIn(List<String> values) {
			addCriterion("drug_name in", values, "drugName");
			return (Criteria) this;
		}

		public Criteria andDrugNameNotIn(List<String> values) {
			addCriterion("drug_name not in", values, "drugName");
			return (Criteria) this;
		}

		public Criteria andDrugNameBetween(String value1, String value2) {
			addCriterion("drug_name between", value1, value2, "drugName");
			return (Criteria) this;
		}

		public Criteria andDrugNameNotBetween(String value1, String value2) {
			addCriterion("drug_name not between", value1, value2, "drugName");
			return (Criteria) this;
		}

		public Criteria andDoseIsNull() {
			addCriterion("dose is null");
			return (Criteria) this;
		}

		public Criteria andDoseIsNotNull() {
			addCriterion("dose is not null");
			return (Criteria) this;
		}

		public Criteria andDoseEqualTo(Double value) {
			addCriterion("dose =", value, "dose");
			return (Criteria) this;
		}

		public Criteria andDoseNotEqualTo(Double value) {
			addCriterion("dose <>", value, "dose");
			return (Criteria) this;
		}

		public Criteria andDoseGreaterThan(Double value) {
			addCriterion("dose >", value, "dose");
			return (Criteria) this;
		}

		public Criteria andDoseGreaterThanOrEqualTo(Double value) {
			addCriterion("dose >=", value, "dose");
			return (Criteria) this;
		}

		public Criteria andDoseLessThan(Double value) {
			addCriterion("dose <", value, "dose");
			return (Criteria) this;
		}

		public Criteria andDoseLessThanOrEqualTo(Double value) {
			addCriterion("dose <=", value, "dose");
			return (Criteria) this;
		}

		public Criteria andDoseIn(List<Double> values) {
			addCriterion("dose in", values, "dose");
			return (Criteria) this;
		}

		public Criteria andDoseNotIn(List<Double> values) {
			addCriterion("dose not in", values, "dose");
			return (Criteria) this;
		}

		public Criteria andDoseBetween(Double value1, Double value2) {
			addCriterion("dose between", value1, value2, "dose");
			return (Criteria) this;
		}

		public Criteria andDoseNotBetween(Double value1, Double value2) {
			addCriterion("dose not between", value1, value2, "dose");
			return (Criteria) this;
		}

		public Criteria andDoseUnitIsNull() {
			addCriterion("dose_unit is null");
			return (Criteria) this;
		}

		public Criteria andDoseUnitIsNotNull() {
			addCriterion("dose_unit is not null");
			return (Criteria) this;
		}

		public Criteria andDoseUnitEqualTo(String value) {
			addCriterion("dose_unit =", value, "doseUnit");
			return (Criteria) this;
		}

		public Criteria andDoseUnitNotEqualTo(String value) {
			addCriterion("dose_unit <>", value, "doseUnit");
			return (Criteria) this;
		}

		public Criteria andDoseUnitGreaterThan(String value) {
			addCriterion("dose_unit >", value, "doseUnit");
			return (Criteria) this;
		}

		public Criteria andDoseUnitGreaterThanOrEqualTo(String value) {
			addCriterion("dose_unit >=", value, "doseUnit");
			return (Criteria) this;
		}

		public Criteria andDoseUnitLessThan(String value) {
			addCriterion("dose_unit <", value, "doseUnit");
			return (Criteria) this;
		}

		public Criteria andDoseUnitLessThanOrEqualTo(String value) {
			addCriterion("dose_unit <=", value, "doseUnit");
			return (Criteria) this;
		}

		public Criteria andDoseUnitLike(String value) {
			addCriterion("dose_unit like", value, "doseUnit");
			return (Criteria) this;
		}

		public Criteria andDoseUnitNotLike(String value) {
			addCriterion("dose_unit not like", value, "doseUnit");
			return (Criteria) this;
		}

		public Criteria andDoseUnitIn(List<String> values) {
			addCriterion("dose_unit in", values, "doseUnit");
			return (Criteria) this;
		}

		public Criteria andDoseUnitNotIn(List<String> values) {
			addCriterion("dose_unit not in", values, "doseUnit");
			return (Criteria) this;
		}

		public Criteria andDoseUnitBetween(String value1, String value2) {
			addCriterion("dose_unit between", value1, value2, "doseUnit");
			return (Criteria) this;
		}

		public Criteria andDoseUnitNotBetween(String value1, String value2) {
			addCriterion("dose_unit not between", value1, value2, "doseUnit");
			return (Criteria) this;
		}

		public Criteria andRateIsNull() {
			addCriterion("rate is null");
			return (Criteria) this;
		}

		public Criteria andRateIsNotNull() {
			addCriterion("rate is not null");
			return (Criteria) this;
		}

		public Criteria andRateEqualTo(Double value) {
			addCriterion("rate =", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateNotEqualTo(Double value) {
			addCriterion("rate <>", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateGreaterThan(Double value) {
			addCriterion("rate >", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateGreaterThanOrEqualTo(Double value) {
			addCriterion("rate >=", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateLessThan(Double value) {
			addCriterion("rate <", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateLessThanOrEqualTo(Double value) {
			addCriterion("rate <=", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateIn(List<Double> values) {
			addCriterion("rate in", values, "rate");
			return (Criteria) this;
		}

		public Criteria andRateNotIn(List<Double> values) {
			addCriterion("rate not in", values, "rate");
			return (Criteria) this;
		}

		public Criteria andRateBetween(Double value1, Double value2) {
			addCriterion("rate between", value1, value2, "rate");
			return (Criteria) this;
		}

		public Criteria andRateNotBetween(Double value1, Double value2) {
			addCriterion("rate not between", value1, value2, "rate");
			return (Criteria) this;
		}

		public Criteria andRateUnitIsNull() {
			addCriterion("rate_unit is null");
			return (Criteria) this;
		}

		public Criteria andRateUnitIsNotNull() {
			addCriterion("rate_unit is not null");
			return (Criteria) this;
		}

		public Criteria andRateUnitEqualTo(String value) {
			addCriterion("rate_unit =", value, "rateUnit");
			return (Criteria) this;
		}

		public Criteria andRateUnitNotEqualTo(String value) {
			addCriterion("rate_unit <>", value, "rateUnit");
			return (Criteria) this;
		}

		public Criteria andRateUnitGreaterThan(String value) {
			addCriterion("rate_unit >", value, "rateUnit");
			return (Criteria) this;
		}

		public Criteria andRateUnitGreaterThanOrEqualTo(String value) {
			addCriterion("rate_unit >=", value, "rateUnit");
			return (Criteria) this;
		}

		public Criteria andRateUnitLessThan(String value) {
			addCriterion("rate_unit <", value, "rateUnit");
			return (Criteria) this;
		}

		public Criteria andRateUnitLessThanOrEqualTo(String value) {
			addCriterion("rate_unit <=", value, "rateUnit");
			return (Criteria) this;
		}

		public Criteria andRateUnitLike(String value) {
			addCriterion("rate_unit like", value, "rateUnit");
			return (Criteria) this;
		}

		public Criteria andRateUnitNotLike(String value) {
			addCriterion("rate_unit not like", value, "rateUnit");
			return (Criteria) this;
		}

		public Criteria andRateUnitIn(List<String> values) {
			addCriterion("rate_unit in", values, "rateUnit");
			return (Criteria) this;
		}

		public Criteria andRateUnitNotIn(List<String> values) {
			addCriterion("rate_unit not in", values, "rateUnit");
			return (Criteria) this;
		}

		public Criteria andRateUnitBetween(String value1, String value2) {
			addCriterion("rate_unit between", value1, value2, "rateUnit");
			return (Criteria) this;
		}

		public Criteria andRateUnitNotBetween(String value1, String value2) {
			addCriterion("rate_unit not between", value1, value2, "rateUnit");
			return (Criteria) this;
		}

		public Criteria andOrderedAsIsNull() {
			addCriterion("ordered_as is null");
			return (Criteria) this;
		}

		public Criteria andOrderedAsIsNotNull() {
			addCriterion("ordered_as is not null");
			return (Criteria) this;
		}

		public Criteria andOrderedAsEqualTo(String value) {
			addCriterion("ordered_as =", value, "orderedAs");
			return (Criteria) this;
		}

		public Criteria andOrderedAsNotEqualTo(String value) {
			addCriterion("ordered_as <>", value, "orderedAs");
			return (Criteria) this;
		}

		public Criteria andOrderedAsGreaterThan(String value) {
			addCriterion("ordered_as >", value, "orderedAs");
			return (Criteria) this;
		}

		public Criteria andOrderedAsGreaterThanOrEqualTo(String value) {
			addCriterion("ordered_as >=", value, "orderedAs");
			return (Criteria) this;
		}

		public Criteria andOrderedAsLessThan(String value) {
			addCriterion("ordered_as <", value, "orderedAs");
			return (Criteria) this;
		}

		public Criteria andOrderedAsLessThanOrEqualTo(String value) {
			addCriterion("ordered_as <=", value, "orderedAs");
			return (Criteria) this;
		}

		public Criteria andOrderedAsLike(String value) {
			addCriterion("ordered_as like", value, "orderedAs");
			return (Criteria) this;
		}

		public Criteria andOrderedAsNotLike(String value) {
			addCriterion("ordered_as not like", value, "orderedAs");
			return (Criteria) this;
		}

		public Criteria andOrderedAsIn(List<String> values) {
			addCriterion("ordered_as in", values, "orderedAs");
			return (Criteria) this;
		}

		public Criteria andOrderedAsNotIn(List<String> values) {
			addCriterion("ordered_as not in", values, "orderedAs");
			return (Criteria) this;
		}

		public Criteria andOrderedAsBetween(String value1, String value2) {
			addCriterion("ordered_as between", value1, value2, "orderedAs");
			return (Criteria) this;
		}

		public Criteria andOrderedAsNotBetween(String value1, String value2) {
			addCriterion("ordered_as not between", value1, value2, "orderedAs");
			return (Criteria) this;
		}

		public Criteria andRouteIsNull() {
			addCriterion("route is null");
			return (Criteria) this;
		}

		public Criteria andRouteIsNotNull() {
			addCriterion("route is not null");
			return (Criteria) this;
		}

		public Criteria andRouteEqualTo(String value) {
			addCriterion("route =", value, "route");
			return (Criteria) this;
		}

		public Criteria andRouteNotEqualTo(String value) {
			addCriterion("route <>", value, "route");
			return (Criteria) this;
		}

		public Criteria andRouteGreaterThan(String value) {
			addCriterion("route >", value, "route");
			return (Criteria) this;
		}

		public Criteria andRouteGreaterThanOrEqualTo(String value) {
			addCriterion("route >=", value, "route");
			return (Criteria) this;
		}

		public Criteria andRouteLessThan(String value) {
			addCriterion("route <", value, "route");
			return (Criteria) this;
		}

		public Criteria andRouteLessThanOrEqualTo(String value) {
			addCriterion("route <=", value, "route");
			return (Criteria) this;
		}

		public Criteria andRouteLike(String value) {
			addCriterion("route like", value, "route");
			return (Criteria) this;
		}

		public Criteria andRouteNotLike(String value) {
			addCriterion("route not like", value, "route");
			return (Criteria) this;
		}

		public Criteria andRouteIn(List<String> values) {
			addCriterion("route in", values, "route");
			return (Criteria) this;
		}

		public Criteria andRouteNotIn(List<String> values) {
			addCriterion("route not in", values, "route");
			return (Criteria) this;
		}

		public Criteria andRouteBetween(String value1, String value2) {
			addCriterion("route between", value1, value2, "route");
			return (Criteria) this;
		}

		public Criteria andRouteNotBetween(String value1, String value2) {
			addCriterion("route not between", value1, value2, "route");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andSiteIsNull() {
			addCriterion("site is null");
			return (Criteria) this;
		}

		public Criteria andSiteIsNotNull() {
			addCriterion("site is not null");
			return (Criteria) this;
		}

		public Criteria andSiteEqualTo(String value) {
			addCriterion("site =", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotEqualTo(String value) {
			addCriterion("site <>", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteGreaterThan(String value) {
			addCriterion("site >", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteGreaterThanOrEqualTo(String value) {
			addCriterion("site >=", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteLessThan(String value) {
			addCriterion("site <", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteLessThanOrEqualTo(String value) {
			addCriterion("site <=", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteLike(String value) {
			addCriterion("site like", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotLike(String value) {
			addCriterion("site not like", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteIn(List<String> values) {
			addCriterion("site in", values, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotIn(List<String> values) {
			addCriterion("site not in", values, "site");
			return (Criteria) this;
		}

		public Criteria andSiteBetween(String value1, String value2) {
			addCriterion("site between", value1, value2, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotBetween(String value1, String value2) {
			addCriterion("site not between", value1, value2, "site");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitIsNull() {
			addCriterion("infused_vol_unit is null");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitIsNotNull() {
			addCriterion("infused_vol_unit is not null");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitEqualTo(String value) {
			addCriterion("infused_vol_unit =", value, "infusedVolUnit");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitNotEqualTo(String value) {
			addCriterion("infused_vol_unit <>", value, "infusedVolUnit");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitGreaterThan(String value) {
			addCriterion("infused_vol_unit >", value, "infusedVolUnit");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitGreaterThanOrEqualTo(String value) {
			addCriterion("infused_vol_unit >=", value, "infusedVolUnit");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitLessThan(String value) {
			addCriterion("infused_vol_unit <", value, "infusedVolUnit");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitLessThanOrEqualTo(String value) {
			addCriterion("infused_vol_unit <=", value, "infusedVolUnit");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitLike(String value) {
			addCriterion("infused_vol_unit like", value, "infusedVolUnit");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitNotLike(String value) {
			addCriterion("infused_vol_unit not like", value, "infusedVolUnit");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitIn(List<String> values) {
			addCriterion("infused_vol_unit in", values, "infusedVolUnit");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitNotIn(List<String> values) {
			addCriterion("infused_vol_unit not in", values, "infusedVolUnit");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitBetween(String value1, String value2) {
			addCriterion("infused_vol_unit between", value1, value2, "infusedVolUnit");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitNotBetween(String value1, String value2) {
			addCriterion("infused_vol_unit not between", value1, value2, "infusedVolUnit");
			return (Criteria) this;
		}

		public Criteria andInfuseIndIsNull() {
			addCriterion("infuse_ind is null");
			return (Criteria) this;
		}

		public Criteria andInfuseIndIsNotNull() {
			addCriterion("infuse_ind is not null");
			return (Criteria) this;
		}

		public Criteria andInfuseIndEqualTo(Integer value) {
			addCriterion("infuse_ind =", value, "infuseInd");
			return (Criteria) this;
		}

		public Criteria andInfuseIndNotEqualTo(Integer value) {
			addCriterion("infuse_ind <>", value, "infuseInd");
			return (Criteria) this;
		}

		public Criteria andInfuseIndGreaterThan(Integer value) {
			addCriterion("infuse_ind >", value, "infuseInd");
			return (Criteria) this;
		}

		public Criteria andInfuseIndGreaterThanOrEqualTo(Integer value) {
			addCriterion("infuse_ind >=", value, "infuseInd");
			return (Criteria) this;
		}

		public Criteria andInfuseIndLessThan(Integer value) {
			addCriterion("infuse_ind <", value, "infuseInd");
			return (Criteria) this;
		}

		public Criteria andInfuseIndLessThanOrEqualTo(Integer value) {
			addCriterion("infuse_ind <=", value, "infuseInd");
			return (Criteria) this;
		}

		public Criteria andInfuseIndIn(List<Integer> values) {
			addCriterion("infuse_ind in", values, "infuseInd");
			return (Criteria) this;
		}

		public Criteria andInfuseIndNotIn(List<Integer> values) {
			addCriterion("infuse_ind not in", values, "infuseInd");
			return (Criteria) this;
		}

		public Criteria andInfuseIndBetween(Integer value1, Integer value2) {
			addCriterion("infuse_ind between", value1, value2, "infuseInd");
			return (Criteria) this;
		}

		public Criteria andInfuseIndNotBetween(Integer value1, Integer value2) {
			addCriterion("infuse_ind not between", value1, value2, "infuseInd");
			return (Criteria) this;
		}

		public Criteria andIvFlagIsNull() {
			addCriterion("iv_flag is null");
			return (Criteria) this;
		}

		public Criteria andIvFlagIsNotNull() {
			addCriterion("iv_flag is not null");
			return (Criteria) this;
		}

		public Criteria andIvFlagEqualTo(Integer value) {
			addCriterion("iv_flag =", value, "ivFlag");
			return (Criteria) this;
		}

		public Criteria andIvFlagNotEqualTo(Integer value) {
			addCriterion("iv_flag <>", value, "ivFlag");
			return (Criteria) this;
		}

		public Criteria andIvFlagGreaterThan(Integer value) {
			addCriterion("iv_flag >", value, "ivFlag");
			return (Criteria) this;
		}

		public Criteria andIvFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("iv_flag >=", value, "ivFlag");
			return (Criteria) this;
		}

		public Criteria andIvFlagLessThan(Integer value) {
			addCriterion("iv_flag <", value, "ivFlag");
			return (Criteria) this;
		}

		public Criteria andIvFlagLessThanOrEqualTo(Integer value) {
			addCriterion("iv_flag <=", value, "ivFlag");
			return (Criteria) this;
		}

		public Criteria andIvFlagIn(List<Integer> values) {
			addCriterion("iv_flag in", values, "ivFlag");
			return (Criteria) this;
		}

		public Criteria andIvFlagNotIn(List<Integer> values) {
			addCriterion("iv_flag not in", values, "ivFlag");
			return (Criteria) this;
		}

		public Criteria andIvFlagBetween(Integer value1, Integer value2) {
			addCriterion("iv_flag between", value1, value2, "ivFlag");
			return (Criteria) this;
		}

		public Criteria andIvFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("iv_flag not between", value1, value2, "ivFlag");
			return (Criteria) this;
		}

		public Criteria andBolusFlagIsNull() {
			addCriterion("bolus_flag is null");
			return (Criteria) this;
		}

		public Criteria andBolusFlagIsNotNull() {
			addCriterion("bolus_flag is not null");
			return (Criteria) this;
		}

		public Criteria andBolusFlagEqualTo(Integer value) {
			addCriterion("bolus_flag =", value, "bolusFlag");
			return (Criteria) this;
		}

		public Criteria andBolusFlagNotEqualTo(Integer value) {
			addCriterion("bolus_flag <>", value, "bolusFlag");
			return (Criteria) this;
		}

		public Criteria andBolusFlagGreaterThan(Integer value) {
			addCriterion("bolus_flag >", value, "bolusFlag");
			return (Criteria) this;
		}

		public Criteria andBolusFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("bolus_flag >=", value, "bolusFlag");
			return (Criteria) this;
		}

		public Criteria andBolusFlagLessThan(Integer value) {
			addCriterion("bolus_flag <", value, "bolusFlag");
			return (Criteria) this;
		}

		public Criteria andBolusFlagLessThanOrEqualTo(Integer value) {
			addCriterion("bolus_flag <=", value, "bolusFlag");
			return (Criteria) this;
		}

		public Criteria andBolusFlagIn(List<Integer> values) {
			addCriterion("bolus_flag in", values, "bolusFlag");
			return (Criteria) this;
		}

		public Criteria andBolusFlagNotIn(List<Integer> values) {
			addCriterion("bolus_flag not in", values, "bolusFlag");
			return (Criteria) this;
		}

		public Criteria andBolusFlagBetween(Integer value1, Integer value2) {
			addCriterion("bolus_flag between", value1, value2, "bolusFlag");
			return (Criteria) this;
		}

		public Criteria andBolusFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("bolus_flag not between", value1, value2, "bolusFlag");
			return (Criteria) this;
		}

		public Criteria andTdripIndIsNull() {
			addCriterion("tdrip_ind is null");
			return (Criteria) this;
		}

		public Criteria andTdripIndIsNotNull() {
			addCriterion("tdrip_ind is not null");
			return (Criteria) this;
		}

		public Criteria andTdripIndEqualTo(Integer value) {
			addCriterion("tdrip_ind =", value, "tdripInd");
			return (Criteria) this;
		}

		public Criteria andTdripIndNotEqualTo(Integer value) {
			addCriterion("tdrip_ind <>", value, "tdripInd");
			return (Criteria) this;
		}

		public Criteria andTdripIndGreaterThan(Integer value) {
			addCriterion("tdrip_ind >", value, "tdripInd");
			return (Criteria) this;
		}

		public Criteria andTdripIndGreaterThanOrEqualTo(Integer value) {
			addCriterion("tdrip_ind >=", value, "tdripInd");
			return (Criteria) this;
		}

		public Criteria andTdripIndLessThan(Integer value) {
			addCriterion("tdrip_ind <", value, "tdripInd");
			return (Criteria) this;
		}

		public Criteria andTdripIndLessThanOrEqualTo(Integer value) {
			addCriterion("tdrip_ind <=", value, "tdripInd");
			return (Criteria) this;
		}

		public Criteria andTdripIndIn(List<Integer> values) {
			addCriterion("tdrip_ind in", values, "tdripInd");
			return (Criteria) this;
		}

		public Criteria andTdripIndNotIn(List<Integer> values) {
			addCriterion("tdrip_ind not in", values, "tdripInd");
			return (Criteria) this;
		}

		public Criteria andTdripIndBetween(Integer value1, Integer value2) {
			addCriterion("tdrip_ind between", value1, value2, "tdripInd");
			return (Criteria) this;
		}

		public Criteria andTdripIndNotBetween(Integer value1, Integer value2) {
			addCriterion("tdrip_ind not between", value1, value2, "tdripInd");
			return (Criteria) this;
		}

		public Criteria andIdLikeInsensitive(String value) {
			addCriterion("upper(id) like", value.toUpperCase(), "id");
			return (Criteria) this;
		}

		public Criteria andDrugNameLikeInsensitive(String value) {
			addCriterion("upper(drug_name) like", value.toUpperCase(), "drugName");
			return (Criteria) this;
		}

		public Criteria andDoseUnitLikeInsensitive(String value) {
			addCriterion("upper(dose_unit) like", value.toUpperCase(), "doseUnit");
			return (Criteria) this;
		}

		public Criteria andRateUnitLikeInsensitive(String value) {
			addCriterion("upper(rate_unit) like", value.toUpperCase(), "rateUnit");
			return (Criteria) this;
		}

		public Criteria andOrderedAsLikeInsensitive(String value) {
			addCriterion("upper(ordered_as) like", value.toUpperCase(), "orderedAs");
			return (Criteria) this;
		}

		public Criteria andRouteLikeInsensitive(String value) {
			addCriterion("upper(route) like", value.toUpperCase(), "route");
			return (Criteria) this;
		}

		public Criteria andStatusLikeInsensitive(String value) {
			addCriterion("upper(status) like", value.toUpperCase(), "status");
			return (Criteria) this;
		}

		public Criteria andSiteLikeInsensitive(String value) {
			addCriterion("upper(site) like", value.toUpperCase(), "site");
			return (Criteria) this;
		}

		public Criteria andInfusedVolUnitLikeInsensitive(String value) {
			addCriterion("upper(infused_vol_unit) like", value.toUpperCase(), "infusedVolUnit");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table medication
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table medication
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}