package edu.pitt.medschool.model.dto;

import java.time.LocalDateTime;

public class Version {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.version_id
	 * @mbg.generated
	 */
	private Integer versionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.create_date
	 * @mbg.generated
	 */
	private LocalDateTime createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.patient_num
	 * @mbg.generated
	 */
	private Long patientNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.csv_file_num
	 * @mbg.generated
	 */
	private Long csvFileNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.medication_num
	 * @mbg.generated
	 */
	private Long medicationNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.patient_increase
	 * @mbg.generated
	 */
	private Long patientIncrease;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.medication_increase
	 * @mbg.generated
	 */
	private Long medicationIncrease;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.csv_increase
	 * @mbg.generated
	 */
	private Long csvIncrease;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.csv_delete
	 * @mbg.generated
	 */
	private Long csvDelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column version.comment
	 * @mbg.generated
	 */
	private String comment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.version_id
	 * @return  the value of version.version_id
	 * @mbg.generated
	 */
	public Integer getVersionId() {
		return versionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.version_id
	 * @param versionId  the value for version.version_id
	 * @mbg.generated
	 */
	public void setVersionId(Integer versionId) {
		this.versionId = versionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.create_date
	 * @return  the value of version.create_date
	 * @mbg.generated
	 */
	public LocalDateTime getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.create_date
	 * @param createDate  the value for version.create_date
	 * @mbg.generated
	 */
	public void setCreateDate(LocalDateTime createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.patient_num
	 * @return  the value of version.patient_num
	 * @mbg.generated
	 */
	public Long getPatientNum() {
		return patientNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.patient_num
	 * @param patientNum  the value for version.patient_num
	 * @mbg.generated
	 */
	public void setPatientNum(Long patientNum) {
		this.patientNum = patientNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.csv_file_num
	 * @return  the value of version.csv_file_num
	 * @mbg.generated
	 */
	public Long getCsvFileNum() {
		return csvFileNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.csv_file_num
	 * @param csvFileNum  the value for version.csv_file_num
	 * @mbg.generated
	 */
	public void setCsvFileNum(Long csvFileNum) {
		this.csvFileNum = csvFileNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.medication_num
	 * @return  the value of version.medication_num
	 * @mbg.generated
	 */
	public Long getMedicationNum() {
		return medicationNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.medication_num
	 * @param medicationNum  the value for version.medication_num
	 * @mbg.generated
	 */
	public void setMedicationNum(Long medicationNum) {
		this.medicationNum = medicationNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.patient_increase
	 * @return  the value of version.patient_increase
	 * @mbg.generated
	 */
	public Long getPatientIncrease() {
		return patientIncrease;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.patient_increase
	 * @param patientIncrease  the value for version.patient_increase
	 * @mbg.generated
	 */
	public void setPatientIncrease(Long patientIncrease) {
		this.patientIncrease = patientIncrease;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.medication_increase
	 * @return  the value of version.medication_increase
	 * @mbg.generated
	 */
	public Long getMedicationIncrease() {
		return medicationIncrease;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.medication_increase
	 * @param medicationIncrease  the value for version.medication_increase
	 * @mbg.generated
	 */
	public void setMedicationIncrease(Long medicationIncrease) {
		this.medicationIncrease = medicationIncrease;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.csv_increase
	 * @return  the value of version.csv_increase
	 * @mbg.generated
	 */
	public Long getCsvIncrease() {
		return csvIncrease;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.csv_increase
	 * @param csvIncrease  the value for version.csv_increase
	 * @mbg.generated
	 */
	public void setCsvIncrease(Long csvIncrease) {
		this.csvIncrease = csvIncrease;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.csv_delete
	 * @return  the value of version.csv_delete
	 * @mbg.generated
	 */
	public Long getCsvDelete() {
		return csvDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.csv_delete
	 * @param csvDelete  the value for version.csv_delete
	 * @mbg.generated
	 */
	public void setCsvDelete(Long csvDelete) {
		this.csvDelete = csvDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column version.comment
	 * @return  the value of version.comment
	 * @mbg.generated
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column version.comment
	 * @param comment  the value for version.comment
	 * @mbg.generated
	 */
	public void setComment(String comment) {
		this.comment = comment == null ? null : comment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Version other = (Version) that;
		return (this.getVersionId() == null ? other.getVersionId() == null
				: this.getVersionId().equals(other.getVersionId()))
				&& (this.getCreateDate() == null ? other.getCreateDate() == null
						: this.getCreateDate().equals(other.getCreateDate()))
				&& (this.getPatientNum() == null ? other.getPatientNum() == null
						: this.getPatientNum().equals(other.getPatientNum()))
				&& (this.getCsvFileNum() == null ? other.getCsvFileNum() == null
						: this.getCsvFileNum().equals(other.getCsvFileNum()))
				&& (this.getMedicationNum() == null ? other.getMedicationNum() == null
						: this.getMedicationNum().equals(other.getMedicationNum()))
				&& (this.getPatientIncrease() == null ? other.getPatientIncrease() == null
						: this.getPatientIncrease().equals(other.getPatientIncrease()))
				&& (this.getMedicationIncrease() == null ? other.getMedicationIncrease() == null
						: this.getMedicationIncrease().equals(other.getMedicationIncrease()))
				&& (this.getCsvIncrease() == null ? other.getCsvIncrease() == null
						: this.getCsvIncrease().equals(other.getCsvIncrease()))
				&& (this.getCsvDelete() == null ? other.getCsvDelete() == null
						: this.getCsvDelete().equals(other.getCsvDelete()))
				&& (this.getComment() == null ? other.getComment() == null
						: this.getComment().equals(other.getComment()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getVersionId() == null) ? 0 : getVersionId().hashCode());
		result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
		result = prime * result + ((getPatientNum() == null) ? 0 : getPatientNum().hashCode());
		result = prime * result + ((getCsvFileNum() == null) ? 0 : getCsvFileNum().hashCode());
		result = prime * result + ((getMedicationNum() == null) ? 0 : getMedicationNum().hashCode());
		result = prime * result + ((getPatientIncrease() == null) ? 0 : getPatientIncrease().hashCode());
		result = prime * result + ((getMedicationIncrease() == null) ? 0 : getMedicationIncrease().hashCode());
		result = prime * result + ((getCsvIncrease() == null) ? 0 : getCsvIncrease().hashCode());
		result = prime * result + ((getCsvDelete() == null) ? 0 : getCsvDelete().hashCode());
		result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
		return result;
	}
}