package edu.pitt.medschool.model.mapper;

import edu.pitt.medschool.model.dto.CsvLog;
import edu.pitt.medschool.model.dto.CsvLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface CsvLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	@SelectProvider(type = CsvLogSqlProvider.class, method = "countByExample")
	long countByExample(CsvLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	@DeleteProvider(type = CsvLogSqlProvider.class, method = "deleteByExample")
	int deleteByExample(CsvLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	@Delete({ "delete from csv_log", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	@Insert({ "insert into csv_log (id, status, ", "activity, timestamp, ", "filename, stat_time, ",
			"end_time, comment)", "values (#{id,jdbcType=INTEGER}, #{status,jdbcType=INTEGER}, ",
			"#{activity,jdbcType=INTEGER}, #{timestamp,jdbcType=TIMESTAMP}, ",
			"#{filename,jdbcType=VARCHAR}, #{statTime,jdbcType=TIMESTAMP}, ",
			"#{endTime,jdbcType=TIMESTAMP}, #{comment,jdbcType=VARCHAR})" })
	int insert(CsvLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	@InsertProvider(type = CsvLogSqlProvider.class, method = "insertSelective")
	int insertSelective(CsvLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	@SelectProvider(type = CsvLogSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
			@Result(column = "activity", property = "activity", jdbcType = JdbcType.INTEGER),
			@Result(column = "timestamp", property = "timestamp", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "filename", property = "filename", jdbcType = JdbcType.VARCHAR),
			@Result(column = "stat_time", property = "statTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "end_time", property = "endTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "comment", property = "comment", jdbcType = JdbcType.VARCHAR) })
	List<CsvLog> selectByExampleWithRowbounds(CsvLogExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	@SelectProvider(type = CsvLogSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
			@Result(column = "activity", property = "activity", jdbcType = JdbcType.INTEGER),
			@Result(column = "timestamp", property = "timestamp", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "filename", property = "filename", jdbcType = JdbcType.VARCHAR),
			@Result(column = "stat_time", property = "statTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "end_time", property = "endTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "comment", property = "comment", jdbcType = JdbcType.VARCHAR) })
	List<CsvLog> selectByExample(CsvLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	@Select({ "select", "id, status, activity, timestamp, filename, stat_time, end_time, comment", "from csv_log",
			"where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
			@Result(column = "activity", property = "activity", jdbcType = JdbcType.INTEGER),
			@Result(column = "timestamp", property = "timestamp", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "filename", property = "filename", jdbcType = JdbcType.VARCHAR),
			@Result(column = "stat_time", property = "statTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "end_time", property = "endTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "comment", property = "comment", jdbcType = JdbcType.VARCHAR) })
	CsvLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	@UpdateProvider(type = CsvLogSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") CsvLog record, @Param("example") CsvLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	@UpdateProvider(type = CsvLogSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") CsvLog record, @Param("example") CsvLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	@UpdateProvider(type = CsvLogSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(CsvLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	@Update({ "update csv_log", "set status = #{status,jdbcType=INTEGER},", "activity = #{activity,jdbcType=INTEGER},",
			"timestamp = #{timestamp,jdbcType=TIMESTAMP},", "filename = #{filename,jdbcType=VARCHAR},",
			"stat_time = #{statTime,jdbcType=TIMESTAMP},", "end_time = #{endTime,jdbcType=TIMESTAMP},",
			"comment = #{comment,jdbcType=VARCHAR}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(CsvLog record);
}