package edu.pitt.medschool.model.mapper;

import edu.pitt.medschool.model.dto.CsvLog;
import edu.pitt.medschool.model.dto.CsvLogExample.Criteria;
import edu.pitt.medschool.model.dto.CsvLogExample.Criterion;
import edu.pitt.medschool.model.dto.CsvLogExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CsvLogSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	public String countByExample(CsvLogExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("csv_log");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	public String deleteByExample(CsvLogExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("csv_log");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	public String insertSelective(CsvLog record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("csv_log");
		if (record.getId() != null) {
			sql.VALUES("id", "#{id,jdbcType=INTEGER}");
		}
		if (record.getStatus() != null) {
			sql.VALUES("status", "#{status,jdbcType=INTEGER}");
		}
		if (record.getActivity() != null) {
			sql.VALUES("activity", "#{activity,jdbcType=INTEGER}");
		}
		if (record.getTimestamp() != null) {
			sql.VALUES("timestamp", "#{timestamp,jdbcType=TIMESTAMP}");
		}
		if (record.getFilename() != null) {
			sql.VALUES("filename", "#{filename,jdbcType=VARCHAR}");
		}
		if (record.getStatTime() != null) {
			sql.VALUES("stat_time", "#{statTime,jdbcType=TIMESTAMP}");
		}
		if (record.getEndTime() != null) {
			sql.VALUES("end_time", "#{endTime,jdbcType=TIMESTAMP}");
		}
		if (record.getComment() != null) {
			sql.VALUES("comment", "#{comment,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	public String selectByExample(CsvLogExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("status");
		sql.SELECT("activity");
		sql.SELECT("timestamp");
		sql.SELECT("filename");
		sql.SELECT("stat_time");
		sql.SELECT("end_time");
		sql.SELECT("comment");
		sql.FROM("csv_log");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		CsvLog record = (CsvLog) parameter.get("record");
		CsvLogExample example = (CsvLogExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("csv_log");
		if (record.getId() != null) {
			sql.SET("id = #{record.id,jdbcType=INTEGER}");
		}
		if (record.getStatus() != null) {
			sql.SET("status = #{record.status,jdbcType=INTEGER}");
		}
		if (record.getActivity() != null) {
			sql.SET("activity = #{record.activity,jdbcType=INTEGER}");
		}
		if (record.getTimestamp() != null) {
			sql.SET("timestamp = #{record.timestamp,jdbcType=TIMESTAMP}");
		}
		if (record.getFilename() != null) {
			sql.SET("filename = #{record.filename,jdbcType=VARCHAR}");
		}
		if (record.getStatTime() != null) {
			sql.SET("stat_time = #{record.statTime,jdbcType=TIMESTAMP}");
		}
		if (record.getEndTime() != null) {
			sql.SET("end_time = #{record.endTime,jdbcType=TIMESTAMP}");
		}
		if (record.getComment() != null) {
			sql.SET("comment = #{record.comment,jdbcType=VARCHAR}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("csv_log");
		sql.SET("id = #{record.id,jdbcType=INTEGER}");
		sql.SET("status = #{record.status,jdbcType=INTEGER}");
		sql.SET("activity = #{record.activity,jdbcType=INTEGER}");
		sql.SET("timestamp = #{record.timestamp,jdbcType=TIMESTAMP}");
		sql.SET("filename = #{record.filename,jdbcType=VARCHAR}");
		sql.SET("stat_time = #{record.statTime,jdbcType=TIMESTAMP}");
		sql.SET("end_time = #{record.endTime,jdbcType=TIMESTAMP}");
		sql.SET("comment = #{record.comment,jdbcType=VARCHAR}");
		CsvLogExample example = (CsvLogExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	public String updateByPrimaryKeySelective(CsvLog record) {
		SQL sql = new SQL();
		sql.UPDATE("csv_log");
		if (record.getStatus() != null) {
			sql.SET("status = #{status,jdbcType=INTEGER}");
		}
		if (record.getActivity() != null) {
			sql.SET("activity = #{activity,jdbcType=INTEGER}");
		}
		if (record.getTimestamp() != null) {
			sql.SET("timestamp = #{timestamp,jdbcType=TIMESTAMP}");
		}
		if (record.getFilename() != null) {
			sql.SET("filename = #{filename,jdbcType=VARCHAR}");
		}
		if (record.getStatTime() != null) {
			sql.SET("stat_time = #{statTime,jdbcType=TIMESTAMP}");
		}
		if (record.getEndTime() != null) {
			sql.SET("end_time = #{endTime,jdbcType=TIMESTAMP}");
		}
		if (record.getComment() != null) {
			sql.SET("comment = #{comment,jdbcType=VARCHAR}");
		}
		sql.WHERE("id = #{id,jdbcType=INTEGER}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upmc..csv_log
	 * @mbg.generated
	 */
	protected void applyWhere(SQL sql, CsvLogExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}