package edu.pitt.medschool.model.mapper;

import edu.pitt.medschool.model.dto.DownsampleGroupColumn;
import edu.pitt.medschool.model.dto.DownsampleGroupColumnExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;
import org.apache.ibatis.annotations.SelectKey;

@Mapper
public interface DownsampleGroupColumnMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_group_column
     * @mbg.generated
     */
    @SelectProvider(type = DownsampleGroupColumnSqlProvider.class, method = "countByExample")
    long countByExample(DownsampleGroupColumnExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_group_column
     * @mbg.generated
     */
    @DeleteProvider(type = DownsampleGroupColumnSqlProvider.class, method = "deleteByExample")
    int deleteByExample(DownsampleGroupColumnExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_group_column
     * @mbg.generated
     */
    @Delete({ "delete from downsample_group_column", "where id = #{id,jdbcType=INTEGER}" })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_group_column
     * @mbg.generated
     */
    @Insert({ "insert into downsample_group_column (query_group_id, column_name)", "values (#{queryGroupId,jdbcType=INTEGER}, #{columnName,jdbcType=VARCHAR})" })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
    int insert(DownsampleGroupColumn record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_group_column
     * @mbg.generated
     */
    @InsertProvider(type = DownsampleGroupColumnSqlProvider.class, method = "insertSelective")
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
    int insertSelective(DownsampleGroupColumn record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_group_column
     * @mbg.generated
     */
    @SelectProvider(type = DownsampleGroupColumnSqlProvider.class, method = "selectByExample")
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "query_group_id", property = "queryGroupId", jdbcType = JdbcType.INTEGER),
            @Result(column = "column_name", property = "columnName", jdbcType = JdbcType.VARCHAR) })
    List<DownsampleGroupColumn> selectByExampleWithRowbounds(DownsampleGroupColumnExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_group_column
     * @mbg.generated
     */
    @SelectProvider(type = DownsampleGroupColumnSqlProvider.class, method = "selectByExample")
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "query_group_id", property = "queryGroupId", jdbcType = JdbcType.INTEGER),
            @Result(column = "column_name", property = "columnName", jdbcType = JdbcType.VARCHAR) })
    List<DownsampleGroupColumn> selectByExample(DownsampleGroupColumnExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_group_column
     * @mbg.generated
     */
    @Select({ "select", "id, query_group_id, column_name", "from downsample_group_column", "where id = #{id,jdbcType=INTEGER}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "query_group_id", property = "queryGroupId", jdbcType = JdbcType.INTEGER),
            @Result(column = "column_name", property = "columnName", jdbcType = JdbcType.VARCHAR) })
    DownsampleGroupColumn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_group_column
     * @mbg.generated
     */
    @UpdateProvider(type = DownsampleGroupColumnSqlProvider.class, method = "updateByExampleSelective")
    int updateByExampleSelective(@Param("record") DownsampleGroupColumn record, @Param("example") DownsampleGroupColumnExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_group_column
     * @mbg.generated
     */
    @UpdateProvider(type = DownsampleGroupColumnSqlProvider.class, method = "updateByExample")
    int updateByExample(@Param("record") DownsampleGroupColumn record, @Param("example") DownsampleGroupColumnExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_group_column
     * @mbg.generated
     */
    @UpdateProvider(type = DownsampleGroupColumnSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DownsampleGroupColumn record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table downsample_group_column
     * @mbg.generated
     */
    @Update({ "update downsample_group_column", "set query_group_id = #{queryGroupId,jdbcType=INTEGER},", "column_name = #{columnName,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKey(DownsampleGroupColumn record);
}