package edu.pitt.medschool.model.mapper;

import edu.pitt.medschool.model.dto.Export;
import edu.pitt.medschool.model.dto.ExportExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface ExportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @SelectProvider(type=ExportSqlProvider.class, method="countByExample")
    long countByExample(ExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @DeleteProvider(type=ExportSqlProvider.class, method="deleteByExample")
    int deleteByExample(ExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @Delete({
        "delete from export",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @Insert({
        "insert into export (query_id, ar, ",
        "query_json, update_time, ",
        "create_time, patient_list)",
        "values (#{queryId,jdbcType=INTEGER}, #{ar,jdbcType=BIT}, ",
        "#{queryJson,jdbcType=INTEGER}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{patientList,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Export record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @InsertProvider(type=ExportSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Export record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @SelectProvider(type=ExportSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="query_id", property="queryId", jdbcType=JdbcType.INTEGER),
        @Result(column="ar", property="ar", jdbcType=JdbcType.BIT),
        @Result(column="query_json", property="queryJson", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="patient_list", property="patientList", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Export> selectByExampleWithBLOBsWithRowbounds(ExportExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @SelectProvider(type=ExportSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="query_id", property="queryId", jdbcType=JdbcType.INTEGER),
        @Result(column="ar", property="ar", jdbcType=JdbcType.BIT),
        @Result(column="query_json", property="queryJson", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="patient_list", property="patientList", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Export> selectByExampleWithBLOBs(ExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @SelectProvider(type=ExportSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="query_id", property="queryId", jdbcType=JdbcType.INTEGER),
        @Result(column="ar", property="ar", jdbcType=JdbcType.BIT),
        @Result(column="query_json", property="queryJson", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Export> selectByExampleWithRowbounds(ExportExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @SelectProvider(type=ExportSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="query_id", property="queryId", jdbcType=JdbcType.INTEGER),
        @Result(column="ar", property="ar", jdbcType=JdbcType.BIT),
        @Result(column="query_json", property="queryJson", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Export> selectByExample(ExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, query_id, ar, query_json, update_time, create_time, patient_list",
        "from export",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="query_id", property="queryId", jdbcType=JdbcType.INTEGER),
        @Result(column="ar", property="ar", jdbcType=JdbcType.BIT),
        @Result(column="query_json", property="queryJson", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="patient_list", property="patientList", jdbcType=JdbcType.LONGVARCHAR)
    })
    Export selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ExportSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Export record, @Param("example") ExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ExportSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") Export record, @Param("example") ExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ExportSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Export record, @Param("example") ExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ExportSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Export record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @Update({
        "update export",
        "set query_id = #{queryId,jdbcType=INTEGER},",
          "ar = #{ar,jdbcType=BIT},",
          "query_json = #{queryJson,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "patient_list = #{patientList,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(Export record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export
     *
     * @mbg.generated
     */
    @Update({
        "update export",
        "set query_id = #{queryId,jdbcType=INTEGER},",
          "ar = #{ar,jdbcType=BIT},",
          "query_json = #{queryJson,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Export record);
}