package edu.pitt.medschool.model.mapper;

import edu.pitt.medschool.model.dto.ImportProgress;
import edu.pitt.medschool.model.dto.ImportProgressExample.Criteria;
import edu.pitt.medschool.model.dto.ImportProgressExample.Criterion;
import edu.pitt.medschool.model.dto.ImportProgressExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ImportProgressSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
	 * @mbg.generated
	 */
	public String countByExample(ImportProgressExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("import_progress");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
	 * @mbg.generated
	 */
	public String deleteByExample(ImportProgressExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("import_progress");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
	 * @mbg.generated
	 */
	public String insertSelective(ImportProgress record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("import_progress");
		if (record.getId() != null) {
			sql.VALUES("id", "#{id,jdbcType=INTEGER}");
		}
		if (record.getUuid() != null) {
			sql.VALUES("uuid", "#{uuid,jdbcType=VARCHAR}");
		}
		if (record.getBatchId() != null) {
			sql.VALUES("batch_id", "#{batchId,jdbcType=VARCHAR}");
		}
		if (record.getFilename() != null) {
			sql.VALUES("filename", "#{filename,jdbcType=VARCHAR}");
		}
		if (record.getStatus() != null) {
			sql.VALUES("status", "#{status,jdbcType=VARCHAR}");
		}
		if (record.getPercent() != null) {
			sql.VALUES("percent", "#{percent,jdbcType=DOUBLE}");
		}
		if (record.getSize() != null) {
			sql.VALUES("size", "#{size,jdbcType=BIGINT}");
		}
		if (record.getCreateTime() != null) {
			sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
		}
		if (record.getUpdateTime() != null) {
			sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
		}
		if (record.getReason() != null) {
			sql.VALUES("reason", "#{reason,jdbcType=LONGVARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
	 * @mbg.generated
	 */
	public String selectByExampleWithBLOBs(ImportProgressExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("uuid");
		sql.SELECT("batch_id");
		sql.SELECT("filename");
		sql.SELECT("status");
		sql.SELECT("percent");
		sql.SELECT("size");
		sql.SELECT("create_time");
		sql.SELECT("update_time");
		sql.SELECT("reason");
		sql.FROM("import_progress");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
	 * @mbg.generated
	 */
	public String selectByExample(ImportProgressExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("uuid");
		sql.SELECT("batch_id");
		sql.SELECT("filename");
		sql.SELECT("status");
		sql.SELECT("percent");
		sql.SELECT("size");
		sql.SELECT("create_time");
		sql.SELECT("update_time");
		sql.FROM("import_progress");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
	 * @mbg.generated
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		ImportProgress record = (ImportProgress) parameter.get("record");
		ImportProgressExample example = (ImportProgressExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("import_progress");
		if (record.getId() != null) {
			sql.SET("id = #{record.id,jdbcType=INTEGER}");
		}
		if (record.getUuid() != null) {
			sql.SET("uuid = #{record.uuid,jdbcType=VARCHAR}");
		}
		if (record.getBatchId() != null) {
			sql.SET("batch_id = #{record.batchId,jdbcType=VARCHAR}");
		}
		if (record.getFilename() != null) {
			sql.SET("filename = #{record.filename,jdbcType=VARCHAR}");
		}
		if (record.getStatus() != null) {
			sql.SET("status = #{record.status,jdbcType=VARCHAR}");
		}
		if (record.getPercent() != null) {
			sql.SET("percent = #{record.percent,jdbcType=DOUBLE}");
		}
		if (record.getSize() != null) {
			sql.SET("size = #{record.size,jdbcType=BIGINT}");
		}
		if (record.getCreateTime() != null) {
			sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
		}
		if (record.getUpdateTime() != null) {
			sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
		}
		if (record.getReason() != null) {
			sql.SET("reason = #{record.reason,jdbcType=LONGVARCHAR}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
	 * @mbg.generated
	 */
	public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("import_progress");
		sql.SET("id = #{record.id,jdbcType=INTEGER}");
		sql.SET("uuid = #{record.uuid,jdbcType=VARCHAR}");
		sql.SET("batch_id = #{record.batchId,jdbcType=VARCHAR}");
		sql.SET("filename = #{record.filename,jdbcType=VARCHAR}");
		sql.SET("status = #{record.status,jdbcType=VARCHAR}");
		sql.SET("percent = #{record.percent,jdbcType=DOUBLE}");
		sql.SET("size = #{record.size,jdbcType=BIGINT}");
		sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
		sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
		sql.SET("reason = #{record.reason,jdbcType=LONGVARCHAR}");
		ImportProgressExample example = (ImportProgressExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
	 * @mbg.generated
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("import_progress");
		sql.SET("id = #{record.id,jdbcType=INTEGER}");
		sql.SET("uuid = #{record.uuid,jdbcType=VARCHAR}");
		sql.SET("batch_id = #{record.batchId,jdbcType=VARCHAR}");
		sql.SET("filename = #{record.filename,jdbcType=VARCHAR}");
		sql.SET("status = #{record.status,jdbcType=VARCHAR}");
		sql.SET("percent = #{record.percent,jdbcType=DOUBLE}");
		sql.SET("size = #{record.size,jdbcType=BIGINT}");
		sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
		sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
		ImportProgressExample example = (ImportProgressExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
	 * @mbg.generated
	 */
	protected void applyWhere(SQL sql, ImportProgressExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}