package edu.pitt.medschool.model.mapper;

import edu.pitt.medschool.model.dto.ImportProgress;
import edu.pitt.medschool.model.dto.ImportProgressExample;
import edu.pitt.medschool.model.dto.ImportProgressKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface ImportProgressMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@SelectProvider(type=ImportProgressSqlProvider.class, method="countByExample") long countByExample(ImportProgressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@DeleteProvider(type=ImportProgressSqlProvider.class, method="deleteByExample") int deleteByExample(ImportProgressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@Delete({"delete from import_progress","where filename = #{filename,jdbcType=VARCHAR}","and timestamp = #{timestamp,jdbcType=TIMESTAMP}","and uuid = #{uuid,jdbcType=VARCHAR}"}) int deleteByPrimaryKey(ImportProgressKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@Insert({"insert into import_progress (filename, timestamp, ","uuid, status, all_percent, ","this_percent, all_file_size, ","this_file_size, file_path)","values (#{filename,jdbcType=VARCHAR}, #{timestamp,jdbcType=TIMESTAMP}, ","#{uuid,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, #{allPercent,jdbcType=DOUBLE}, ","#{thisPercent,jdbcType=DOUBLE}, #{allFileSize,jdbcType=BIGINT}, ","#{thisFileSize,jdbcType=BIGINT}, #{filePath,jdbcType=VARCHAR})"}) int insert(ImportProgress record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@InsertProvider(type=ImportProgressSqlProvider.class, method="insertSelective") int insertSelective(ImportProgress record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@SelectProvider(type=ImportProgressSqlProvider.class, method="selectByExample") @Results({@Result(column="filename", property="filename", jdbcType=JdbcType.VARCHAR, id=true),@Result(column="timestamp", property="timestamp", jdbcType=JdbcType.TIMESTAMP, id=true),@Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),@Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),@Result(column="all_percent", property="allPercent", jdbcType=JdbcType.DOUBLE),@Result(column="this_percent", property="thisPercent", jdbcType=JdbcType.DOUBLE),@Result(column="all_file_size", property="allFileSize", jdbcType=JdbcType.BIGINT),@Result(column="this_file_size", property="thisFileSize", jdbcType=JdbcType.BIGINT),@Result(column="file_path", property="filePath", jdbcType=JdbcType.VARCHAR)}) List<ImportProgress> selectByExampleWithRowbounds(ImportProgressExample example,RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@SelectProvider(type=ImportProgressSqlProvider.class, method="selectByExample") @Results({@Result(column="filename", property="filename", jdbcType=JdbcType.VARCHAR, id=true),@Result(column="timestamp", property="timestamp", jdbcType=JdbcType.TIMESTAMP, id=true),@Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),@Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),@Result(column="all_percent", property="allPercent", jdbcType=JdbcType.DOUBLE),@Result(column="this_percent", property="thisPercent", jdbcType=JdbcType.DOUBLE),@Result(column="all_file_size", property="allFileSize", jdbcType=JdbcType.BIGINT),@Result(column="this_file_size", property="thisFileSize", jdbcType=JdbcType.BIGINT),@Result(column="file_path", property="filePath", jdbcType=JdbcType.VARCHAR)}) List<ImportProgress> selectByExample(ImportProgressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@Select({"select","filename, timestamp, uuid, status, all_percent, this_percent, all_file_size, ","this_file_size, file_path","from import_progress","where filename = #{filename,jdbcType=VARCHAR}","and timestamp = #{timestamp,jdbcType=TIMESTAMP}","and uuid = #{uuid,jdbcType=VARCHAR}"}) @Results({@Result(column="filename", property="filename", jdbcType=JdbcType.VARCHAR, id=true),@Result(column="timestamp", property="timestamp", jdbcType=JdbcType.TIMESTAMP, id=true),@Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),@Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),@Result(column="all_percent", property="allPercent", jdbcType=JdbcType.DOUBLE),@Result(column="this_percent", property="thisPercent", jdbcType=JdbcType.DOUBLE),@Result(column="all_file_size", property="allFileSize", jdbcType=JdbcType.BIGINT),@Result(column="this_file_size", property="thisFileSize", jdbcType=JdbcType.BIGINT),@Result(column="file_path", property="filePath", jdbcType=JdbcType.VARCHAR)}) ImportProgress selectByPrimaryKey(ImportProgressKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@UpdateProvider(type=ImportProgressSqlProvider.class, method="updateByExampleSelective") int updateByExampleSelective(@Param("record") ImportProgress record,@Param("example") ImportProgressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@UpdateProvider(type=ImportProgressSqlProvider.class, method="updateByExample") int updateByExample(@Param("record") ImportProgress record,@Param("example") ImportProgressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@UpdateProvider(type=ImportProgressSqlProvider.class, method="updateByPrimaryKeySelective") int updateByPrimaryKeySelective(ImportProgress record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table import_progress
     * @mbg.generated
     */@Update({"update import_progress","set status = #{status,jdbcType=VARCHAR},","all_percent = #{allPercent,jdbcType=DOUBLE},","this_percent = #{thisPercent,jdbcType=DOUBLE},","all_file_size = #{allFileSize,jdbcType=BIGINT},","this_file_size = #{thisFileSize,jdbcType=BIGINT},","file_path = #{filePath,jdbcType=VARCHAR}","where filename = #{filename,jdbcType=VARCHAR}","and timestamp = #{timestamp,jdbcType=TIMESTAMP}","and uuid = #{uuid,jdbcType=VARCHAR}"}) int updateByPrimaryKey(ImportProgress record);
}