package edu.pitt.medschool.model.mapper;

import edu.pitt.medschool.model.dto.Milestone;
import edu.pitt.medschool.model.dto.MilestoneExample.Criteria;
import edu.pitt.medschool.model.dto.MilestoneExample.Criterion;
import edu.pitt.medschool.model.dto.MilestoneExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class MilestoneSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table milestone
	 * @mbg.generated
	 */
	public String countByExample(MilestoneExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("milestone");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table milestone
	 * @mbg.generated
	 */
	public String deleteByExample(MilestoneExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("milestone");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table milestone
	 * @mbg.generated
	 */
	public String insertSelective(Milestone record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("milestone");
		if (record.getId() != null) {
			sql.VALUES("id", "#{id,jdbcType=INTEGER}");
		}
		if (record.getDate() != null) {
			sql.VALUES("date", "#{date,jdbcType=TIMESTAMP}");
		}
		if (record.getNumpatients() != null) {
			sql.VALUES("numPatients", "#{numpatients,jdbcType=INTEGER}");
		}
		if (record.getNumcsv() != null) {
			sql.VALUES("numCSV", "#{numcsv,jdbcType=INTEGER}");
		}
		if (record.getType() != null) {
			sql.VALUES("type", "#{type,jdbcType=TINYINT}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table milestone
	 * @mbg.generated
	 */
	public String selectByExample(MilestoneExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("date");
		sql.SELECT("numPatients");
		sql.SELECT("numCSV");
		sql.SELECT("type");
		sql.FROM("milestone");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table milestone
	 * @mbg.generated
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		Milestone record = (Milestone) parameter.get("record");
		MilestoneExample example = (MilestoneExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("milestone");
		if (record.getId() != null) {
			sql.SET("id = #{record.id,jdbcType=INTEGER}");
		}
		if (record.getDate() != null) {
			sql.SET("date = #{record.date,jdbcType=TIMESTAMP}");
		}
		if (record.getNumpatients() != null) {
			sql.SET("numPatients = #{record.numpatients,jdbcType=INTEGER}");
		}
		if (record.getNumcsv() != null) {
			sql.SET("numCSV = #{record.numcsv,jdbcType=INTEGER}");
		}
		if (record.getType() != null) {
			sql.SET("type = #{record.type,jdbcType=TINYINT}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table milestone
	 * @mbg.generated
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("milestone");
		sql.SET("id = #{record.id,jdbcType=INTEGER}");
		sql.SET("date = #{record.date,jdbcType=TIMESTAMP}");
		sql.SET("numPatients = #{record.numpatients,jdbcType=INTEGER}");
		sql.SET("numCSV = #{record.numcsv,jdbcType=INTEGER}");
		sql.SET("type = #{record.type,jdbcType=TINYINT}");
		MilestoneExample example = (MilestoneExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table milestone
	 * @mbg.generated
	 */
	protected void applyWhere(SQL sql, MilestoneExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}