package edu.pitt.medschool.model.mapper;

import edu.pitt.medschool.model.dto.Patient;
import edu.pitt.medschool.model.dto.PatientExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface PatientMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient
     * @mbg.generated
     */
    @SelectProvider(type = PatientSqlProvider.class, method = "countByExample")
    long countByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient
     * @mbg.generated
     */
    @DeleteProvider(type = PatientSqlProvider.class, method = "deleteByExample")
    int deleteByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient
     * @mbg.generated
     */
    @Delete({ "delete from patient", "where id = #{id,jdbcType=VARCHAR}" })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient
     * @mbg.generated
     */
    @Insert({ "insert into patient (id, gender, ", "age)", "values (#{id,jdbcType=VARCHAR}, #{gender,jdbcType=CHAR}, ", "#{age,jdbcType=INTEGER})" })
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient
     * @mbg.generated
     */
    @InsertProvider(type = PatientSqlProvider.class, method = "insertSelective")
    int insertSelective(Patient record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient
     * @mbg.generated
     */
    @SelectProvider(type = PatientSqlProvider.class, method = "selectByExample")
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.VARCHAR, id = true), @Result(column = "gender", property = "gender", jdbcType = JdbcType.CHAR), @Result(column = "age", property = "age", jdbcType = JdbcType.INTEGER) })
    List<Patient> selectByExampleWithRowbounds(PatientExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient
     * @mbg.generated
     */
    @SelectProvider(type = PatientSqlProvider.class, method = "selectByExample")
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.VARCHAR, id = true), @Result(column = "gender", property = "gender", jdbcType = JdbcType.CHAR), @Result(column = "age", property = "age", jdbcType = JdbcType.INTEGER) })
    List<Patient> selectByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient
     * @mbg.generated
     */
    @Select({ "select", "id, gender, age", "from patient", "where id = #{id,jdbcType=VARCHAR}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.VARCHAR, id = true), @Result(column = "gender", property = "gender", jdbcType = JdbcType.CHAR), @Result(column = "age", property = "age", jdbcType = JdbcType.INTEGER) })
    Patient selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient
     * @mbg.generated
     */
    @UpdateProvider(type = PatientSqlProvider.class, method = "updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Patient record, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient
     * @mbg.generated
     */
    @UpdateProvider(type = PatientSqlProvider.class, method = "updateByExample")
    int updateByExample(@Param("record") Patient record, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient
     * @mbg.generated
     */
    @UpdateProvider(type = PatientSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Patient record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient
     * @mbg.generated
     */
    @Update({ "update patient", "set gender = #{gender,jdbcType=CHAR},", "age = #{age,jdbcType=INTEGER}", "where id = #{id,jdbcType=VARCHAR}" })
    int updateByPrimaryKey(Patient record);
}